server:
  port: 15001

spring:
  redis:
    database: 0
    password: admin123456
    timeout: 5000
    cluster:
      max-redirects: 3
      nodes: 10.0.0.87:6479,10.0.0.87:6480,10.0.0.9:6479,10.0.0.9:6480,10.0.0.82:6479,10.0.0.82:6480
#      nodes: 10.0.0.7:6381,10.0.0.7:6382,10.0.0.7:6383,10.0.0.7:6384,10.0.0.7:6385,10.0.0.7:6386
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms